server:
  address: ":8080"

rules:
  - request:
      path: ^/hello$
    response:
      code: 200
      body: "Hello from HTTP Mock Service"
  - request:
      path: ^/hello_with_delay$
    response:
      code: 200
      delay: 5s
      body: "Hello from HTTP Mock Service with delay"
  - request:
      path: ^/hello_json$
    response:
      code: 200
      headers:
        Content-Type: application/json
        Cache-Control: no-cache
        X-Powered-By: http-mock-servie
      body: |
        {
            "product_id": "12345",
            "name": "Wireless Bluetooth Headphones",
            "brand": "TechSound",
            "price": 79.99,
        }
