server:
  host: 0.0.0.0
  port: 8080

rules:
  - request:
      path: ^/hello$
    response:
      code: 200
      body: "Hello from HTTP Mock Service"
  - request:
      path: ^/hello_with_delay$
    response:
      code: 200
      delay: 5s
      body: "Hello from HTTP Mock Service with delay"
  - request:
      path: ^/hello_json$
    response:
      code: 200
      headers:
        Content-Type: application/json
        Cache-Control: no-cache
        X-Powered-By: http-mock-service
      body: |
        {
            "product_id": "12345",
            "name": "Wireless Bluetooth Headphones",
            "brand": "TechSound",
            "price": 79.99,
        }
  - request:
      path: ^/hello_xml$
    response:
      code: 200
      headers:
        Content-Type: application/xml
        Cache-Control: no-cache
        X-Powered-By: http-mock-service
      body: |
        <product>
          <product_id>12345</product_id>
          <name>Wireless Bluetooth Headphones</name>
          <brand>TechSound</brand>
          <price>79.99</price>
        </product
